title: Vandana Kaarthik # your name (or website title) here
#logo: "/images/updated_saree_photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  An NLP Data Science enthusiast and a dedicated, self-driven individual with 9 years of professional experience 
  <br>
  working for top companies in the Automotive, Telecommunication and Printing domain 
  <br><br>
  
  <a href="https://www.linkedin.com/in/vandanakaarthik/">View My LinkedIn Profile</a> 
  
# remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
